[project]
name = "nndl-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gaurang Gupta", email = "gaurangrgupta@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "soundfile>=0.14.0",
]

[project.scripts]
neural-networks-and-deep-learning-project = "neural_networks_and_deep_learning_project:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "jupyterlab>=4.6.4",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "soundfile>=0.14.0",
]
